"""empty message
Revision ID: 3aa589b3bc53
Revises: 
Create Date: 2023-03-12 15:57:34.434451
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa589b3bc53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=True),
                    sa.Column('description', sa.String(
                        length=250), nullable=True),
                    sa.Column('rooms', sa.String(length=80), nullable=True),
                    sa.Column('bathrooms', sa.String(
                        length=80), nullable=True),
                    sa.Column('price', sa.String(length=100), nullable=True),
                    sa.Column('location', sa.String(
                        length=400), nullable=True),
                    sa.Column('pType', sa.String(length=80), nullable=True),
                    sa.Column('image', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
